export interface ColorsPrimitive {
    aliceblue: string;
    antiquewhite: string;
    aqua: string;
    aquamarine: string;
    azure: string;
    beige: string;
    bisque: string;
    black: string;
    blanchedalmond: string;
    blue: string;
    blueviolet: string;
    brown: string;
    burlywood: string;
    cadetblue: string;
    chartreuse: string;
    chocolate: string;
    coral: string;
    cornflowerblue: string;
    cornsilk: string;
    crimson: string;
    cyan: string;
    darkblue: string;
    darkcyan: string;
    darkgoldenrod: string;
    darkgray: string;
    darkgreen: string;
    darkkhaki: string;
    darkmagenta: string;
    darkolivegreen: string;
    darkorange: string;
    darkorchid: string;
    darkred: string;
    darksalmon: string;
    darkseagreen: string;
    darkslateblue: string;
    darkslategray: string;
    darkturquoise: string;
    darkviolet: string;
    deeppink: string;
    deepskyblue: string;
    dimgray: string;
    dodgerblue: string;
    firebrick: string;
    floralwhite: string;
    forestgreen: string;
    fuchsia: string;
    gainsboro: string;
    ghostwhite: string;
    gold: string;
    goldenrod: string;
    gray: string;
    green: string;
    greenyellow: string;
    honeydew: string;
    hotpink: string;
    indianred: string;
    indigo: string;
    ivory: string;
    khaki: string;
    lavender: string;
    lavenderblush: string;
    lawngreen: string;
    lemonchiffon: string;
    lightblue: string;
    lightcoral: string;
    lightcyan: string;
    lightgoldenrodyellow: string;
    lightgray: string;
    lightgreen: string;
    lightpink: string;
    lightsalmon: string;
    lightseagreen: string;
    lightskyblue: string;
    lightslategray: string;
    lightsteelblue: string;
    lightyellow: string;
    lime: string;
    limegreen: string;
    linen: string;
    magenta: string;
    maroon: string;
    mediumaquamarine: string;
    mediumblue: string;
    mediumorchid: string;
    mediumpurple: string;
    mediumseagreen: string;
    mediumslateblue: string;
    mediumspringgreen: string;
    mediumturquoise: string;
    mediumvioletred: string;
    midnightblue: string;
    mintcream: string;
    mistyrose: string;
    moccasin: string;
    navajowhite: string;
    navy: string;
    oldlace: string;
    olive: string;
    olivedrab: string;
    orange: string;
    orangered: string;
    orchid: string;
    palegoldenrod: string;
    palegreen: string;
    paleturquoise: string;
    palevioletred: string;
    papayawhip: string;
    peachpuff: string;
    peru: string;
    pink: string;
    plum: string;
    powderblue: string;
    purple: string;
    rebeccapurple: string;
    red: string;
    rosybrown: string;
    royalblue: string;
    saddlebrown: string;
    salmon: string;
    sandybrown: string;
    seagreen: string;
    seashell: string;
    sienna: string;
    silver: string;
    skyblue: string;
    slateblue: string;
    slategray: string;
    snow: string;
    springgreen: string;
    steelblue: string;
    tan: string;
    teal: string;
    thistle: string;
    tomato: string;
    turquoise: string;
    violet: string;
    wheat: string;
    white: string;
    whitesmoke: string;
    yellow: string;
    yellowgreen: string;
}


export default function Colors(): ColorsPrimitive {
    return {
        aliceblue: 'aliceblue',
        antiquewhite: 'antiquewhite',
        aqua: 'aqua',
        aquamarine: 'aquamarine',
        azure: 'azure',
        beige: 'beige',
        bisque: 'bisque',
        black: 'black',
        blanchedalmond: 'blanchedalmond',
        blue: 'blue',
        blueviolet: 'blueviolet',
        brown: 'brown',
        burlywood: 'burlywood',
        cadetblue: 'cadetblue',
        chartreuse: 'chartreuse',
        chocolate: 'chocolate',
        coral: 'coral',
        cornflowerblue: 'cornflowerblue',
        cornsilk: 'cornsilk',
        crimson: 'crimson',
        cyan: 'cyan',
        darkblue: 'darkblue',
        darkcyan: 'darkcyan',
        darkgoldenrod: 'darkgoldenrod',
        darkgray: 'darkgray',
        darkgreen: 'darkgreen',
        darkkhaki: 'darkkhaki',
        darkmagenta: 'darkmagenta',
        darkolivegreen: 'darkolivegreen',
        darkorange: 'darkorange',
        darkorchid: 'darkorchid',
        darkred: 'darkred',
        darksalmon: 'darksalmon',
        darkseagreen: 'darkseagreen',
        darkslateblue: 'darkslateblue',
        darkslategray: 'darkslategray',
        darkturquoise: 'darkturquoise',
        darkviolet: 'darkviolet',
        deeppink: 'deeppink',
        deepskyblue: 'deepskyblue',
        dimgray: 'dimgray',
        dodgerblue: 'dodgerblue',
        firebrick: 'firebrick',
        floralwhite: 'floralwhite',
        forestgreen: 'forestgreen',
        fuchsia: 'fuchsia',
        gainsboro: 'gainsboro',
        ghostwhite: 'ghostwhite',
        gold: 'gold',
        goldenrod: 'goldenrod',
        gray: 'gray',
        green: 'green',
        greenyellow: 'greenyellow',
        honeydew: 'honeydew',
        hotpink: 'hotpink',
        indianred: 'indianred',
        indigo: 'indigo',
        ivory: 'ivory',
        khaki: 'khaki',
        lavender: 'lavender',
        lavenderblush: 'lavenderblush',
        lawngreen: 'lawngreen',
        lemonchiffon: 'lemonchiffon',
        lightblue: 'lightblue',
        lightcoral: 'lightcoral',
        lightcyan: 'lightcyan',
        lightgoldenrodyellow: 'lightgoldenrodyellow',
        lightgray: 'lightgray',
        lightgreen: 'lightgreen',
        lightpink: 'lightpink',
        lightsalmon: 'lightsalmon',
        lightseagreen: 'lightseagreen',
        lightskyblue: 'lightskyblue',
        lightslategray: 'lightslategray',
        lightsteelblue: 'lightsteelblue',
        lightyellow: 'lightyellow',
        lime: 'lime',
        limegreen: 'limegreen',
        linen: 'linen',
        magenta: 'magenta',
        maroon: 'maroon',
        mediumaquamarine: 'mediumaquamarine',
        mediumblue: 'mediumblue',
        mediumorchid: 'mediumorchid',
        mediumpurple: 'mediumpurple',
        mediumseagreen: 'mediumseagreen',
        mediumslateblue: 'mediumslateblue',
        mediumspringgreen: 'mediumspringgreen',
        mediumturquoise: 'mediumturquoise',
        mediumvioletred: 'mediumvioletred',
        midnightblue: 'midnightblue',
        mintcream: 'mintcream',
        mistyrose: 'mistyrose',
        moccasin: 'moccasin',
        navajowhite: 'navajowhite',
        navy: 'navy',
        oldlace: 'oldlace',
        olive: 'olive',
        olivedrab: 'olivedrab',
        orange: 'orange',
        orangered: 'orangered',
        orchid: 'orchid',
        palegoldenrod: 'palegoldenrod',
        palegreen: 'palegreen',
        paleturquoise: 'paleturquoise',
        palevioletred: 'palevioletred',
        papayawhip: 'papayawhip',
        peachpuff: 'peachpuff',
        peru: 'peru',
        pink: 'pink',
        plum: 'plum',
        powderblue: 'powderblue',
        purple: 'purple',
        rebeccapurple: 'rebeccapurple',
        red: 'red',
        rosybrown: 'rosybrown',
        royalblue: 'royalblue',
        saddlebrown: 'saddlebrown',
        salmon: 'salmon',
        sandybrown: 'sandybrown',
        seagreen: 'seagreen',
        seashell: 'seashell',
        sienna: 'sienna',
        silver: 'silver',
        skyblue: 'skyblue',
        slateblue: 'slateblue',
        slategray: 'slategray',
        snow: 'snow',
        springgreen: 'springgreen',
        steelblue: 'steelblue',
        tan: 'tan',
        teal: 'teal',
        thistle: 'thistle',
        tomato: 'tomato',
        turquoise: 'turquoise',
        violet: 'violet',
        wheat: 'wheat',
        white: 'white',
        whitesmoke: 'whitesmoke',
        yellow: 'yellow',
        yellowgreen: 'yellowgreen',
    }
}
